In [1]:
import numpy as np
array=np.array([1,2,3,4,5])
print("the array is", array)
list=array.tolist()
print("the list is", list)




the array is [1 2 3 4 5]
the list is [1, 2, 3, 4, 5]


In [2]:
array1=([9,8,2])
array2=([6,3,7])
array3=([4,1,5])
x=array1[1]
y=array2[1]
z=array3[2]
a=x+y+z
print(a)

16


In [7]:
#question3
import numpy as np
a = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(a)
y=10
print("Values bigger than 10 =", a[a>y])






Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]


In [6]:
#question4
import numpy as np
a=np.array([[3.7],[7.9]],dtype=np.float64)
b=np.array([[3.7],[7.9]],dtype=np.float64)
z=a+b
print(z)




[[ 7.4]
 [15.8]]


In [5]:
#question5
import numpy as np
X = np.random.rand(5, 10)
Y=X-X.mean(axis=1, keepdims=True)
print(Y)

[[-0.09608474  0.56560934 -0.0291246  -0.18746713  0.24002617 -0.04493287
  -0.29464035 -0.2494451  -0.29361325  0.38967254]
 [ 0.2283568  -0.02796536  0.28263409  0.30500066 -0.36066249  0.26724359
   0.23236033 -0.27273028 -0.49672623 -0.1575111 ]
 [ 0.33536029 -0.12850717  0.23144271 -0.37643403 -0.28857979 -0.01638236
   0.27533358 -0.25487063 -0.10847876  0.33111616]
 [-0.52694916  0.03332749  0.19707994  0.10779178 -0.51227201  0.06736093
  -0.15625681  0.35245328  0.23962036  0.1978442 ]
 [-0.32576611 -0.03496965  0.50431611  0.45132968 -0.25946732 -0.25733783
   0.08822624  0.14475707  0.12492322 -0.4360114 ]]
